@startuml
actor Supervisor
participant JoyStick
participant Voice
participant ControlPanel
participant CoordinatorState
participant GlobalPlanner
participant RemoteP3AT
actor P3ATRobot
== 人机协作：以语音控制，出错后手动控制介入，故障解除后恢复任务为例 ==
group 人机交互
Supervisor <-> ControlPanel : Interact with ControlPanel
ControlPanel -> CoordinatorState : P3AT_Panel_Msg.lvclass
CoordinatorState -> CoordinatorState : GoToGuidingMsg.lvclass
Supervisor <-> Voice : Interact with Voice
end
group 语音控制
Voice -> ControlPanel : Semantic_Voice_Array_Msg.lvclass
ControlPanel -> CoordinatorState : Semantic_Voice_Array_Msg.lvclass
CoordinatorState -> GlobalPlanner : Semantic_Voice_Array_Msg.lvclass
GlobalPlanner -> CoordinatorState : LocalGoalMsg.lvclass
CoordinatorState -> RemoteP3AT : LocalGoalMsg.lvclass
actor P3ATRobot
RemoteP3AT <-> P3ATRobot : Interact with P3ATRobot
end
group 手动控制介入
RemoteP3AT -> CoordinatorState : sensor_Msg.lvclass
CoordinatorState -> CoordinatorState : GoToReadyMsg.lvclass
CoordinatorState -> ControlPanel : P3AT_Panel_Msg.lvclass
ControlPanel <-> Supervisor : Interact with ControlPanel
ControlPanel -> CoordinatorState : GoToManualMsg.lvclass
JoyStick -> CoordinatorState : XBOX_Control_Msg.lvclass
CoordinatorState -> RemoteP3AT : vel_cal_Msg.lvclass
RemoteP3AT <-> P3ATRobot : Interact with P3ATRobot
end
group 恢复任务
Supervisor <-> ControlPanel : Interact with ControlPanel
ControlPanel -> CoordinatorState : GoToGuidingMsg.lvclass
end
@enduml